from sqlmodel import SQLModel, Field
from typing import Optional

class IP710Validator(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)  # Auto-increment primary key
    company_name: str
    address: str
    email: str
    liaison_officer: str
    ssn: str
    tel: str
    fax: str
    legal_form: str
    cfc: str
    business_type: str
    business_function: str
    branches: str
    branches_yes: str
    closing_date: str
    start_year: int
    end_year: int
    total_income_1: float
    total_income_2: float
    incomes_service_1: float
    incomes_service_2: float
    incomes_from_persons_1: float
    incomes_from_persons_2: float
    incomes_from_industries_1: float
    incomes_from_industries_2: float
    incomes_from_sales_1: float
    incomes_from_sales_2: float
    income_rent_machinery_1: float
    income_rent_machinery_2: float
    income_rent_land_1: float
    income_rent_land_2: float
    income_interests_1: float
    income_interests_2: float
    income_capital_gain_or_loss_1: float
    income_capital_gain_or_loss_2: float
    income_other_operating_1: float
    income_other_operating_2: float
    total_expenses_1: float
    total_expenses_2: float
    expenses_salaries_1: float
    expenses_salaries_2: float
    expenses_interests_1: float
    expenses_interests_2: float
    expenses_rent_land_1: float
    expenses_rent_land_2: float
    expenses_depreciation_1: float
    expenses_depreciation_2: float
    expenses_bad_debts_1: float
    expenses_bad_debts_2: float
    expenses_donations_1: float
    expenses_donations_2: float
    expenses_other_operating_1: float
    expenses_other_operating_2: float
    expenses_sales_and_use_1: float
    expenses_sales_and_use_2: float
    expenses_purchases_machinery_1: float
    expenses_purchases_machinery_2: float
    expenses_other_purchases_1: float
    expenses_other_purchases_2: float
    expenses_licenses_1: float
    expenses_licenses_2: float
    profit_incomes_tax_1: float
    profit_incomes_tax_2: float
    profit_after_income_tax_1: float
    profit_after_income_tax_2: float
    sales_tax_withheld_1: float
    sales_tax_withheld_2: float
    name: str
    rank: str
