from sqlmodel import SQLModel, Field
from typing import Optional

class IP720Validator(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)  # Auto-increment primary key
    company_name: str
    address: str
    email: str
    liaison_officer: str
    ssn: str
    tel: str
    fax: str
    legal_form: str
    cfc: str
    closing_date: str
    start_year: int
    end_year: int
    total_incomes_1: float
    total_incomes_2: float
    incomes_from_persons_1: float
    incomes_from_persons_2: float
    incomes_from_industries_1: float
    incomes_from_industries_2: float
    incomes_room_rental_1: float
    incomes_room_rental_2: float
    incomes_casino_1: float
    incomes_casino_2: float
    incomes_less_prizes_1: float
    incomes_less_prizes_2: float
    incomes_food_beverages_1: float
    incomes_food_beverages_2: float
    incomes_interests_1: float
    incomes_interests_2: float
    incomes_rent_1: float
    incomes_rent_2: float
    incomes_capital_gain_loss_1: float
    incomes_capital_gain_loss_2: float
    other_incomes_1: float
    other_incomes_2: float
    total_expenses_1: float
    total_expenses_2: float
    expenses_food_beverages_1: float
    expenses_food_beverages_2: float
    expenses_food_1: float
    expenses_food_2: float
    expenses_beverages_1: float
    expenses_beverages_2: float
    expenses_music_entertainment_1: float
    expenses_music_entertainment_2: float
    expenses_salaries_wages_bonus_1: float
    expenses_salaries_wages_bonus_2: float
    expenses_uniform_1: float
    expenses_uniform_2: float
    expenses_interests_1: float
    expenses_interests_2: float
    expenses_rent_1: float
    expenses_rent_2: float
    expenses_depreciation_1: float
    expenses_depreciation_2: float
    expenses_bad_debts_1: float
    expenses_bad_debts_2: float
    expenses_donations_1: float
    expenses_donations_2: float
    expenses_free_food_employees_1: float
    expenses_free_food_employees_2: float
    expenses_sales_tax_1: float
    expenses_sales_tax_2: float
    expenses_purchases_machinery_1: float
    expenses_purchases_machinery_2: float
    expenses_other_purchases_1: float
    expenses_other_purchases_2: float
    expenses_licenses_1: float
    expenses_licenses_2: float
    other_expenses_1: float
    other_expenses_2: float
    net_profit_loss_1: float
    net_profit_loss_2: float
    profit_incomes_tax_1: float
    profit_incomes_tax_2: float
    profit_after_income_tax_1: float
    profit_after_income_tax_2: float
    sales_tax_withheld_1: float
    sales_tax_withheld_2: float
    name: str
    rank: str
